// Generated by CoffeeScript 1.7.1

/*
This program is distributed under the terms of the MIT license.
Copyright 2012 - 2014 (c) Markus Kohlhase <mail@markus-kohlhase.de>
 */

(function() {
  var countComments, countMixed, emptyLines, endOfLine, getCommentExpressions, getStop, getType, keys, lineSum, newLines, nonEmptyLine, slocModule, trampoline,
    __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

  keys = ['total', 'source', 'comment', 'single', 'block', 'mixed', 'empty'];

  nonEmptyLine = /[^\s]/;

  endOfLine = /$/m;

  newLines = /\n/g;

  emptyLines = /^\s*$/mg;

  getCommentExpressions = function(lang) {
    var single, start, stop;
    single = (function() {
      switch (lang) {
        case "coffee":
        case "py":
        case "ls":
        case "rb":
          return /\#/;
        case "js":
        case "c":
        case "cc":
        case "cpp":
        case "h":
        case "hpp":
        case "hx":
        case "ino":
        case "java":
        case "php":
        case "php5":
        case "go":
        case "scss":
        case "less":
        case "styl":
        case "scala":
          return /\/{2}/;
        case "lua":
          return /--/;
        case "erl":
          return /\%/;
        case "monkey":
          return /'/;
        default:
          return null;
      }
    })();
    switch (lang) {
      case "coffee":
        start = stop = /\#{3}/;
        break;
      case "js":
      case "c":
      case "cc":
      case "cpp":
      case "h":
      case "hpp":
      case "hx":
      case "ino":
      case "java":
      case "ls":
      case "php":
      case "php5":
      case "go":
      case "css":
      case "scss":
      case "less":
      case "styl":
      case "scala":
        start = /\/\*+/;
        stop = /\*\/{1}/;
        break;
      case "python":
      case "py":
        start = stop = /\"{3}|\'{3}/;
        break;
      case "html":
        start = /<\!--/;
        stop = /-->/;
        break;
      case "lua":
        start = /--\[{2}/;
        stop = /--\]{2}/;
        break;
      case "erl":
        start = stop = null;
        break;
      case "monkey":
        start = /#rem/i;
        stop = /#end/i;
        break;
      case "rb":
        start = /\=begin/;
        stop = /\=end/;
        break;
      default:
        throw new TypeError("File extension '" + lang + "' is not supported");
    }
    return {
      start: start,
      stop: stop,
      single: single
    };
  };

  countMixed = function(lines, idx, startIdx, res) {
    var i;
    if (nonEmptyLine.exec(lines[0]) && idx !== 0) {
      res.mixed.push({
        start: idx,
        stop: idx
      });
    }
    if ((i = startIdx - idx) !== 0 && nonEmptyLine.exec(lines[i])) {
      return res.mixed.push({
        start: startIdx,
        stop: startIdx
      });
    }
  };

  getStop = function(comment, type, regex) {
    return comment.match((function() {
      switch (type) {
        case 'single':
          return endOfLine;
        case 'block':
          return regex.stop;
      }
    })());
  };

  getType = function(single, start) {
    if (single && !start) {
      return 'single';
    } else if (start && !single) {
      return 'block';
    } else {
      if (start.index <= single.index) {
        return 'block';
      } else {
        return 'single';
      }
    }
  };

  countComments = function(code, regex) {
    var myself;
    myself = function(code, idx, res) {
      var cContentIdx, comment, len, lines, match, single, splitAt, start, startIdx, stop, type, _ref, _ref1, _ref2;
      if (code === '') {
        return res;
      }
      start = (_ref = regex.start) != null ? _ref.exec(code) : void 0;
      single = (_ref1 = regex.single) != null ? _ref1.exec(code) : void 0;
      if (!(start || single)) {
        countMixed(code.split('\n'), idx, idx, res);
        return res;
      }
      type = getType(single, start);
      match = (function() {
        switch (type) {
          case 'single':
            return single;
          case 'block':
            return start;
        }
      })();
      cContentIdx = match.index + match[0].length;
      comment = code.substring(cContentIdx);
      lines = code.substring(0, match.index).split('\n');
      startIdx = lines.length - 1 + idx;
      stop = getStop(comment, type, regex);
      if (!stop) {
        res.error = true;
        return res;
      }
      comment = comment.substring(0, stop.index);
      len = ((_ref2 = comment.match(newLines)) != null ? _ref2.length : void 0) || 0;
      splitAt = cContentIdx + comment.length + stop[0].length;
      code = code.substring(splitAt);
      countMixed(lines, idx, startIdx, res);
      res[type].push({
        start: startIdx,
        stop: startIdx + len
      });
      return function() {
        return myself(code, startIdx + len, res);
      };
    };
    return trampoline(myself(code, 0, {
      single: [],
      block: [],
      mixed: []
    }));
  };

  trampoline = function(next) {
    while (typeof next === 'function') {
      next = next();
    }
    return next;
  };

  lineSum = function(comments) {
    var c, d, i, sum, _i, _len, _ref;
    sum = 0;
    for (i = _i = 0, _len = comments.length; _i < _len; i = ++_i) {
      c = comments[i];
      d = (c.stop - c.start) + 1;
      if (((_ref = comments[i + 1]) != null ? _ref.start : void 0) === c.stop) {
        d--;
      }
      sum += d;
    }
    return sum;
  };

  slocModule = function(code, lang) {
    var b, bIdx, block, comment, empty, mixed, res, s, single, source, total, _i, _len, _ref, _ref1, _ref2, _ref3;
    if (typeof code !== "string") {
      throw new TypeError("'code' has to be a string");
    }
    code = code.replace(/\r/g, '');
    total = 1 + ((_ref = code.match(newLines)) != null ? _ref.length : void 0) || 0;
    empty = ((_ref1 = code.match(emptyLines)) != null ? _ref1.length : void 0) || 0;
    res = countComments(code, getCommentExpressions(lang));
    single = lineSum(res.single);
    block = lineSum(res.block);
    mixed = lineSum(res.mixed);
    comment = block + single;
    bIdx = (function() {
      var _i, _len, _ref2, _ref3, _results;
      _ref2 = res.block;
      _results = [];
      for (_i = 0, _len = _ref2.length; _i < _len; _i++) {
        b = _ref2[_i];
        if (!(_ref3 = b.stop, __indexOf.call(_results, _ref3) >= 0)) {
          _results.push(b.stop);
        }
      }
      return _results;
    })();
    _ref2 = res.single;
    for (_i = 0, _len = _ref2.length; _i < _len; _i++) {
      s = _ref2[_i];
      if (_ref3 = s.start, __indexOf.call(bIdx, _ref3) >= 0) {
        comment--;
      }
    }
    source = total - comment - empty + mixed;
    return {
      total: total,
      source: source,
      comment: comment,
      single: single,
      block: block,
      mixed: mixed,
      empty: empty
    };
  };

  slocModule.extensions = ["c", "cc", "coffee", "cpp", "css", "erl", "go", "h", "hpp", "html", "hx", "ino", "java", "js", "less", "lua", "ls", "monkey", "php", "php5", "py", "rb", "scala", "scss", "styl"];

  slocModule.keys = keys;

  if ((typeof define !== "undefined" && define !== null ? define.amd : void 0) != null) {
    define(function() {
      return slocModule;
    });
  } else if ((typeof module !== "undefined" && module !== null ? module.exports : void 0) != null) {
    module.exports = slocModule;
  } else if (typeof window !== "undefined" && window !== null) {
    window.sloc = slocModule;
  }

}).call(this);
